// Mock data for AI War feed
window.AIWAR_DATA = (function() {
  const SOURCES = [
    { id: 'openai', name: 'OpenAI', domain: 'openai.com', color: 'openai', logo: 'assets/openai-logo.webp' },
    { id: 'anthropic', name: 'Anthropic', domain: 'anthropic.com', color: 'anthropic', logo: 'assets/anthropic-logo.png' },
    { id: 'deepmind', name: 'Google DeepMind', domain: 'deepmind.google', color: 'deepmind', logo: 'assets/deepmind-logo.webp' },
  ];

  const CATEGORIES = [
    { id: 'all', name: 'All articles', icon: 'layers' },
    { id: 'models', name: 'Models & Releases', icon: 'cpu' },
    { id: 'research', name: 'Research', icon: 'flask' },
    { id: 'product', name: 'Product & Platform', icon: 'box' },
    { id: 'safety', name: 'Safety & Alignment', icon: 'shield' },
    { id: 'science', name: 'Science & Applications', icon: 'microscope' },
    { id: 'policy', name: 'Policy & Society', icon: 'scale' },
    { id: 'company', name: 'Company & Partnerships', icon: 'building' },
    { id: 'announcements', name: 'Announcements', icon: 'megaphone' },
  ];

  // Date helpers — generate articles with realistic recent timestamps
  const now = new Date('2026-05-26T14:00:00Z');
  const hoursAgo = (h) => new Date(now.getTime() - h * 3600 * 1000).toISOString();

  const ARTICLES = [
    {
      id: 'a01',
      title: 'Claude 4.5 Sonnet: extended reasoning and a 1M-token context window',
      excerpt: 'Today we are releasing Claude 4.5 Sonnet, our most capable model for coding and long-horizon agentic tasks. The model introduces deliberate reasoning at inference time and ships with a one-million-token context, available across the API and Claude apps.',
      url: 'https://anthropic.com/news/claude-4-5-sonnet',
      source_id: 'anthropic',
      author: 'Anthropic Team',
      category: 'models',
      published_at: hoursAgo(2),
      featured: true,
      hero: 'aurora',
      read_min: 6,
    },
    {
      id: 'a02',
      title: 'Introducing GPT-5o: native multimodality and real-time voice',
      excerpt: 'GPT-5o reasons across text, audio, vision, and video in a single model. It responds to voice in 232ms on average and matches GPT-4 Turbo on text benchmarks at half the latency.',
      url: 'https://openai.com/blog/gpt-5o',
      source_id: 'openai',
      author: 'OpenAI',
      category: 'models',
      published_at: hoursAgo(5),
      hero: 'spiral',
      read_min: 8,
    },
    {
      id: 'a03',
      title: 'Gemini 2.5 Deep Think: scaling test-time reasoning to scientific discovery',
      excerpt: 'A new variant of Gemini 2.5 that explores multiple hypotheses in parallel before responding. It tops the IMO 2025 problem set and surfaces novel material candidates from raw experimental data.',
      url: 'https://deepmind.google/blog/gemini-2-5-deep-think',
      source_id: 'deepmind',
      author: 'Google DeepMind',
      category: 'research',
      published_at: hoursAgo(9),
      hero: 'grid',
      read_min: 12,
    },
    {
      id: 'a04',
      title: 'Responsible Scaling Policy v3: thresholds for autonomous AI R&D',
      excerpt: 'We are updating our Responsible Scaling Policy with new evaluations for AI systems capable of meaningful autonomous research. The policy adds explicit deployment and security commitments at ASL-4.',
      url: 'https://anthropic.com/news/rsp-v3',
      source_id: 'anthropic',
      category: 'safety',
      author: 'Policy Team',
      published_at: hoursAgo(14),
      hero: 'shield',
      read_min: 10,
    },
    {
      id: 'a05',
      title: 'OpenAI for Government: building secure AI for the U.S. public sector',
      excerpt: 'A new tier of ChatGPT designed for federal, state, and local agencies, with FedRAMP High in process and dedicated infrastructure.',
      url: 'https://openai.com/blog/openai-for-government',
      source_id: 'openai',
      category: 'company',
      author: 'OpenAI',
      published_at: hoursAgo(18),
      hero: 'capitol',
      read_min: 5,
    },
    {
      id: 'a06',
      title: 'AlphaFold 4 expands to protein–RNA and small-molecule complexes',
      excerpt: 'The next generation of AlphaFold predicts the structure and interactions of all molecules of life with state-of-the-art accuracy, including RNA, ligands, and post-translational modifications.',
      url: 'https://deepmind.google/blog/alphafold-4',
      source_id: 'deepmind',
      category: 'science',
      author: 'AlphaFold Team',
      published_at: hoursAgo(24),
      hero: 'helix',
      read_min: 14,
    },
    {
      id: 'a07',
      title: 'Computer use API: agents that drive a virtual desktop',
      excerpt: 'Claude can now move cursors, click buttons, and type text in a sandboxed environment. We are releasing a public beta of the computer-use tool with safety guardrails and rate limits.',
      url: 'https://anthropic.com/news/computer-use-api',
      source_id: 'anthropic',
      category: 'product',
      author: 'Product Team',
      published_at: hoursAgo(36),
      hero: 'desktop',
      read_min: 7,
    },
    {
      id: 'a08',
      title: 'Preparedness framework update: cybersecurity and biorisk evaluations',
      excerpt: 'We are publishing the v3 preparedness framework with refined thresholds for cyber-offensive capability, autonomous replication, and model self-exfiltration. Includes results from the latest red-team exercise.',
      url: 'https://openai.com/blog/preparedness-v3',
      source_id: 'openai',
      category: 'safety',
      author: 'Preparedness Team',
      published_at: hoursAgo(42),
      hero: 'lattice',
      read_min: 11,
    },
    {
      id: 'a09',
      title: 'Gemma 3: open weights, 27B parameters, runs on a single GPU',
      excerpt: 'Our latest open-weight family is competitive with closed frontier models on reasoning and code while fitting on consumer hardware. Released under an updated, permissive license.',
      url: 'https://deepmind.google/blog/gemma-3',
      source_id: 'deepmind',
      category: 'models',
      author: 'Gemma Team',
      published_at: hoursAgo(50),
      hero: 'cube',
      read_min: 6,
    },
    {
      id: 'a10',
      title: 'Economic Index: where Claude shows up in the labor market',
      excerpt: 'A first-of-its-kind look at how AI is being used across U.S. occupations, drawn from anonymized Claude.ai conversations. Software, writing, and analysis dominate; the long tail is broader than expected.',
      url: 'https://anthropic.com/economic-index',
      source_id: 'anthropic',
      category: 'policy',
      author: 'Societal Impacts',
      published_at: hoursAgo(60),
      hero: 'bars',
      read_min: 9,
    },
    {
      id: 'a11',
      title: 'New developer tools: structured outputs, prompt caching, and batch API',
      excerpt: 'Three additions to the OpenAI API: a JSON-schema mode that guarantees valid outputs, automatic prompt caching for repeated prefixes, and a batch endpoint at 50% the cost.',
      url: 'https://openai.com/blog/dev-tools',
      source_id: 'openai',
      category: 'product',
      author: 'Developer Platform',
      published_at: hoursAgo(72),
      hero: 'code',
      read_min: 4,
    },
    {
      id: 'a12',
      title: 'Project Astra: a universal AI assistant that sees and remembers',
      excerpt: 'A research preview of an agent that combines real-time vision, long-term memory, and tool use across phone and glasses form factors. Early access begins this quarter.',
      url: 'https://deepmind.google/blog/project-astra',
      source_id: 'deepmind',
      category: 'product',
      author: 'Astra Team',
      published_at: hoursAgo(80),
      hero: 'eye',
      read_min: 8,
    },
    {
      id: 'a13',
      title: 'Sparse autoencoders find universal concepts across model scales',
      excerpt: 'New interpretability research shows that the same high-level features — deception, sycophancy, code-switching — emerge in both 7B and 400B-parameter models, suggesting shared representational primitives.',
      url: 'https://anthropic.com/research/sae-universal',
      source_id: 'anthropic',
      category: 'research',
      author: 'Interpretability Team',
      published_at: hoursAgo(96),
      hero: 'neurons',
      read_min: 16,
    },
    {
      id: 'a14',
      title: 'Sora 2: cinematic video generation with controllable physics',
      excerpt: 'Sora 2 generates up to two minutes of 1080p video from text or image prompts, with new controls for camera, lighting, and physical simulation. Rolling out to ChatGPT Pro and Enterprise.',
      url: 'https://openai.com/blog/sora-2',
      source_id: 'openai',
      category: 'product',
      author: 'OpenAI',
      published_at: hoursAgo(108),
      hero: 'film',
      read_min: 6,
    },
    {
      id: 'a15',
      title: 'Partnership with the U.K. AI Safety Institute on pre-deployment testing',
      excerpt: 'A new agreement gives the U.K. AI Safety Institute early access to frontier models for independent capability and safety evaluation prior to public release.',
      url: 'https://deepmind.google/blog/aisi-partnership',
      source_id: 'deepmind',
      category: 'company',
      author: 'Policy & Public Affairs',
      published_at: hoursAgo(120),
      hero: 'handshake',
      read_min: 4,
    },
    {
      id: 'a16',
      title: 'Announcing the Anthropic Fellows Program — Summer 2026 cohort',
      excerpt: 'A six-month fellowship for researchers transitioning into AI safety, with compute, mentorship, and a stipend. Applications open through July.',
      url: 'https://anthropic.com/news/fellows-2026',
      source_id: 'anthropic',
      category: 'announcements',
      author: 'Anthropic',
      published_at: hoursAgo(140),
      hero: 'star',
      read_min: 3,
    },
  ];

  const TOPICS = [
    { id: 't1', name: 'Reasoning', trend: 94, hot: true },
    { id: 't2', name: 'Agents', trend: 87, hot: true },
    { id: 't3', name: 'Multimodality', trend: 76 },
    { id: 't4', name: 'Interpretability', trend: 62 },
    { id: 't5', name: 'Open weights', trend: 58 },
    { id: 't6', name: 'Voice', trend: 51 },
    { id: 't7', name: 'Long context', trend: 47 },
    { id: 't8', name: 'AlphaFold', trend: 44 },
    { id: 't9', name: 'Computer use', trend: 41 },
    { id: 't10', name: 'RSP / Preparedness', trend: 38 },
    { id: 't11', name: 'Video gen', trend: 33 },
    { id: 't12', name: 'Economic impact', trend: 27 },
  ];

  const MOST_READ = [
    { id: 'a02', title: 'Introducing GPT-5o: native multimodality and real-time voice', source: 'openai', views: '24.1k' },
    { id: 'a01', title: 'Claude 4.5 Sonnet: extended reasoning and a 1M-token context window', source: 'anthropic', views: '19.8k' },
    { id: 'a06', title: 'AlphaFold 4 expands to protein–RNA and small-molecule complexes', source: 'deepmind', views: '15.2k' },
    { id: 'a14', title: 'Sora 2: cinematic video generation with controllable physics', source: 'openai', views: '12.7k' },
    { id: 'a04', title: 'Responsible Scaling Policy v3: thresholds for autonomous AI R&D', source: 'anthropic', views: '9.4k' },
  ];

  return { SOURCES, CATEGORIES, ARTICLES, TOPICS, MOST_READ, now };
})();
